spring:
  profiles:
    active: db, core, wx
  messages:
    encoding: UTF-8

server:
  port: 5050

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    com.lixin.litemall.wx:  DEBUG
    com.lixin.litemall:  ERROR

swagger:
  production: false
